title: HackOttawa
description: > # this means to ignore newlines until "baseurl:"
  Biggest Hackathon in Ottawa|Joint Carleton University, University of Ottawa and Algonquin College|Students Hackathon in Ottawa, Canada.
baseurl: "" # the subpath of your site, e.g. /blog
url: "hackottawa.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2017_style/img/icon-large.png"

social: 
  name: HackOttwa
  link: "https://www.facebook.com/HackOttwa"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/hackottawa
  - title: twitter
    url: https://twitter.com/hackottawa
  - title: linkedin
    url: https://www.linkedin.com/company/hackottawa
  - title: instagram
    url: https://instagram.com/hack.ottwa

# Build settings
markdown: kramdown
permalink: pretty
